/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\01_Projects\\Personal\\blogs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-5bb6f808",
    path: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E7%88%AC%E8%99%AB%E8%B1%86%E7%93%A3top250%E5%AE%9E%E6%88%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5bb6f808").then(next)
    },
  },
  {
    path: "/blogs/AI程序设计实训/数据爬取/scrapy框架爬虫豆瓣top250实战.html",
    redirect: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E7%88%AC%E8%99%AB%E8%B1%86%E7%93%A3top250%E5%AE%9E%E6%88%98.html"
  },
  {
    path: "/blogs/AI程序设计实训/数据爬取/scrapy框架爬虫豆瓣top250实战.html",
    redirect: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E7%88%AC%E8%99%AB%E8%B1%86%E7%93%A3top250%E5%AE%9E%E6%88%98.html"
  },
  {
    name: "v-66154f4d",
    path: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66154f4d").then(next)
    },
  },
  {
    path: "/blogs/AI程序设计实训/数据爬取/scrapy框架基础操作.html",
    redirect: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C.html"
  },
  {
    path: "/blogs/AI程序设计实训/数据爬取/scrapy框架基础操作.html",
    redirect: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C.html"
  },
  {
    name: "v-0d5c6368",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d5c6368").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-4d9f03a0",
    path: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E7%88%AC%E5%8F%96%E5%B0%8F%E7%BA%A2%E4%B9%A6%E5%AE%9E%E6%88%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d9f03a0").then(next)
    },
  },
  {
    path: "/blogs/AI程序设计实训/数据爬取/scrapy爬取小红书实战.html",
    redirect: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E7%88%AC%E5%8F%96%E5%B0%8F%E7%BA%A2%E4%B9%A6%E5%AE%9E%E6%88%98.html"
  },
  {
    path: "/blogs/AI程序设计实训/数据爬取/scrapy爬取小红书实战.html",
    redirect: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E7%88%AC%E5%8F%96%E5%B0%8F%E7%BA%A2%E4%B9%A6%E5%AE%9E%E6%88%98.html"
  },
  {
    name: "v-53e1722a",
    path: "/blogs/%E5%8D%9A%E5%AE%A2/%E6%84%9F%E6%83%B3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53e1722a").then(next)
    },
  },
  {
    path: "/blogs/博客/感想.html",
    redirect: "/blogs/%E5%8D%9A%E5%AE%A2/%E6%84%9F%E6%83%B3.html"
  },
  {
    path: "/blogs/博客/感想.html",
    redirect: "/blogs/%E5%8D%9A%E5%AE%A2/%E6%84%9F%E6%83%B3.html"
  },
  {
    name: "v-10e06d68",
    path: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/xpath.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10e06d68").then(next)
    },
  },
  {
    path: "/blogs/AI程序设计实训/数据爬取/xpath.html",
    redirect: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/xpath.html"
  },
  {
    path: "/blogs/AI程序设计实训/数据爬取/xpath.html",
    redirect: "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/xpath.html"
  },
  {
    name: "v-0ecdade6",
    path: "/blogs/%E5%8D%9A%E5%AE%A2/1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ecdade6").then(next)
    },
  },
  {
    path: "/blogs/博客/1.html",
    redirect: "/blogs/%E5%8D%9A%E5%AE%A2/1.html"
  },
  {
    path: "/blogs/博客/1.html",
    redirect: "/blogs/%E5%8D%9A%E5%AE%A2/1.html"
  },
  {
    name: "v-64ac6d72",
    path: "/blogs/%E5%8D%9A%E5%AE%A2/%E6%B8%B8%E6%88%8F%E6%B5%8B%E8%AF%84/%E6%8D%9E%E5%A5%B3%E6%B8%B8%E6%88%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64ac6d72").then(next)
    },
  },
  {
    path: "/blogs/博客/游戏测评/捞女游戏.html",
    redirect: "/blogs/%E5%8D%9A%E5%AE%A2/%E6%B8%B8%E6%88%8F%E6%B5%8B%E8%AF%84/%E6%8D%9E%E5%A5%B3%E6%B8%B8%E6%88%8F.html"
  },
  {
    path: "/blogs/博客/游戏测评/捞女游戏.html",
    redirect: "/blogs/%E5%8D%9A%E5%AE%A2/%E6%B8%B8%E6%88%8F%E6%B5%8B%E8%AF%84/%E6%8D%9E%E5%A5%B3%E6%B8%B8%E6%88%8F.html"
  },
  {
    name: "v-09512f34",
    path: "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/venv.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-09512f34").then(next)
    },
  },
  {
    path: "/blogs/编程环境搭建/python环境搭建/venv.html",
    redirect: "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/venv.html"
  },
  {
    path: "/blogs/编程环境搭建/python环境搭建/venv.html",
    redirect: "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/venv.html"
  },
  {
    name: "v-40324584",
    path: "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89tabBar%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-40324584").then(next)
    },
  },
  {
    path: "/blogs/微信小程序开发/微信小程序自定义tabBar教程.html",
    redirect: "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89tabBar%E6%95%99%E7%A8%8B.html"
  },
  {
    path: "/blogs/微信小程序开发/微信小程序自定义tabBar教程.html",
    redirect: "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89tabBar%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-67a046ad",
    path: "/blogs/%E7%BD%91%E7%AB%99%E5%BB%BA%E8%AE%BE/vuepress%E7%83%AD%E9%87%8D%E8%BD%BD%E4%B8%8D%E6%88%90%E5%8A%9F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67a046ad").then(next)
    },
  },
  {
    path: "/blogs/网站建设/vuepress热重载不成功.html",
    redirect: "/blogs/%E7%BD%91%E7%AB%99%E5%BB%BA%E8%AE%BE/vuepress%E7%83%AD%E9%87%8D%E8%BD%BD%E4%B8%8D%E6%88%90%E5%8A%9F.html"
  },
  {
    path: "/blogs/网站建设/vuepress热重载不成功.html",
    redirect: "/blogs/%E7%BD%91%E7%AB%99%E5%BB%BA%E8%AE%BE/vuepress%E7%83%AD%E9%87%8D%E8%BD%BD%E4%B8%8D%E6%88%90%E5%8A%9F.html"
  },
  {
    name: "v-7562d230",
    path: "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/conda.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7562d230").then(next)
    },
  },
  {
    path: "/blogs/编程环境搭建/python环境搭建/conda.html",
    redirect: "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/conda.html"
  },
  {
    path: "/blogs/编程环境搭建/python环境搭建/conda.html",
    redirect: "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/conda.html"
  },
  {
    name: "v-2663ebee",
    path: "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E7%BB%8F%E9%AA%8C%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2663ebee").then(next)
    },
  },
  {
    path: "/blogs/微信小程序开发/微信小程序开发经验总结.html",
    redirect: "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E7%BB%8F%E9%AA%8C%E6%80%BB%E7%BB%93.html"
  },
  {
    path: "/blogs/微信小程序开发/微信小程序开发经验总结.html",
    redirect: "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E7%BB%8F%E9%AA%8C%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-e8d9abc6",
    path: "/tag/AI/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e8d9abc6").then(next)
    },
    meta: {"pid":"tags","id":"AI"}
  },
  {
    path: "/tag/AI/index.html",
    redirect: "/tag/AI/"
  },
  {
    name: "v-1eedfa34",
    path: "/tag/随笔/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1eedfa34").then(next)
    },
    meta: {"pid":"tags","id":"随笔"}
  },
  {
    path: "/tag/随笔/index.html",
    redirect: "/tag/随笔/"
  },
  {
    name: "v-0cf33b9b",
    path: "/tag/计算机/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0cf33b9b").then(next)
    },
    meta: {"pid":"tags","id":"计算机"}
  },
  {
    path: "/tag/计算机/index.html",
    redirect: "/tag/计算机/"
  },
  {
    name: "v-57230139",
    path: "/tag/网站建设/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-57230139").then(next)
    },
    meta: {"pid":"tags","id":"网站建设"}
  },
  {
    path: "/tag/网站建设/index.html",
    redirect: "/tag/网站建设/"
  },
  {
    name: "v-1571e677",
    path: "/tag/游戏/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1571e677").then(next)
    },
    meta: {"pid":"tags","id":"游戏"}
  },
  {
    path: "/tag/游戏/index.html",
    redirect: "/tag/游戏/"
  },
  {
    name: "v-309cc62e",
    path: "/tag/python/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-309cc62e").then(next)
    },
    meta: {"pid":"tags","id":"python"}
  },
  {
    path: "/tag/python/index.html",
    redirect: "/tag/python/"
  },
  {
    name: "v-e003d3f8",
    path: "/tag/环境配置/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e003d3f8").then(next)
    },
    meta: {"pid":"tags","id":"环境配置"}
  },
  {
    path: "/tag/环境配置/index.html",
    redirect: "/tag/环境配置/"
  },
  {
    name: "v-5e08fc30",
    path: "/tag/VuePress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5e08fc30").then(next)
    },
    meta: {"pid":"tags","id":"VuePress"}
  },
  {
    path: "/tag/VuePress/index.html",
    redirect: "/tag/VuePress/"
  },
  {
    name: "v-bb7c1530",
    path: "/categories/AI程序设计实训/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-bb7c1530").then(next)
    },
    meta: {"pid":"categories","id":"AI程序设计实训"}
  },
  {
    path: "/categories/AI程序设计实训/index.html",
    redirect: "/categories/AI程序设计实训/"
  },
  {
    name: "v-42aee080",
    path: "/categories/博客/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-42aee080").then(next)
    },
    meta: {"pid":"categories","id":"博客"}
  },
  {
    path: "/categories/博客/index.html",
    redirect: "/categories/博客/"
  },
  {
    name: "v-720cd23e",
    path: "/categories/游戏测评/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-720cd23e").then(next)
    },
    meta: {"pid":"categories","id":"游戏测评"}
  },
  {
    path: "/categories/游戏测评/index.html",
    redirect: "/categories/游戏测评/"
  },
  {
    name: "v-997b0f8e",
    path: "/categories/编程环境配置/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-997b0f8e").then(next)
    },
    meta: {"pid":"categories","id":"编程环境配置"}
  },
  {
    path: "/categories/编程环境配置/index.html",
    redirect: "/categories/编程环境配置/"
  },
  {
    name: "v-2370bb68",
    path: "/categories/微信小程序/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-2370bb68").then(next)
    },
    meta: {"pid":"categories","id":"微信小程序"}
  },
  {
    path: "/categories/微信小程序/index.html",
    redirect: "/categories/微信小程序/"
  },
  {
    name: "v-55a3a745",
    path: "/categories/网站建设/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-55a3a745").then(next)
    },
    meta: {"pid":"categories","id":"网站建设"}
  },
  {
    path: "/categories/网站建设/index.html",
    redirect: "/categories/网站建设/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]