/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Captain的博客",
  "description": "这里是captain的个人博客，主要记录自己的编程经验，欢迎大家交流分享",
  "base": "/blogs/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/blogs/captain.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "scrapy框架爬虫豆瓣top250实战",
      "frontmatter": {
        "title": "scrapy框架爬虫豆瓣top250实战",
        "date": "2025-06-30T00:00:00.000Z",
        "categories": [
          "AI程序设计实训"
        ],
        "tags": [
          "AI"
        ]
      },
      "regularPath": "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E7%88%AC%E8%99%AB%E8%B1%86%E7%93%A3top250%E5%AE%9E%E6%88%98.html",
      "relativePath": "blogs/AI程序设计实训/数据爬取/scrapy框架爬虫豆瓣top250实战.md",
      "key": "v-5bb6f808",
      "path": "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E7%88%AC%E8%99%AB%E8%B1%86%E7%93%A3top250%E5%AE%9E%E6%88%98.html"
    },
    {
      "title": "scrapy框架基础操作",
      "frontmatter": {
        "title": "scrapy框架基础操作",
        "date": "2025-06-30T00:00:00.000Z",
        "categories": [
          "AI程序设计实训"
        ],
        "tags": [
          "AI"
        ]
      },
      "regularPath": "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C.html",
      "relativePath": "blogs/AI程序设计实训/数据爬取/scrapy框架基础操作.md",
      "key": "v-66154f4d",
      "path": "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E6%A1%86%E6%9E%B6%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C.html",
      "headers": [
        {
          "level": 2,
          "title": "终端操作",
          "slug": "终端操作"
        },
        {
          "level": 2,
          "title": "爬虫流程",
          "slug": "爬虫流程"
        },
        {
          "level": 2,
          "title": "scrapy保存信息的最简单的方法主要有四种，-o 输出指定格式的文件，命令如下：",
          "slug": "scrapy保存信息的最简单的方法主要有四种-o-输出指定格式的文件-命令如下"
        },
        {
          "level": 3,
          "title": "json lines格式，默认为Unicode编码",
          "slug": "json-lines格式-默认为unicode编码"
        },
        {
          "level": 3,
          "title": "csv 逗号表达式，可用Excel打开",
          "slug": "csv-逗号表达式-可用excel打开"
        },
        {
          "level": 3,
          "title": "xml格式",
          "slug": "xml格式"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/满穗.png",
        "heroText": "Captain",
        "heroTextStyle": {
          "color": "#42b983",
          "fontSize": "2.5rem"
        },
        "heroImageStyle": {
          "maxHeight": "300px",
          "display": "block",
          "borderRadius": "19% 81% 23% 77% / 44% 57% 43% 56%",
          "boxShadow": "0 15px 18px rgba(255, 254, 254, 0.2)",
          "margin": "0 auto",
          "marginBottom": "100px",
          "marginTop": "100px"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-0d5c6368",
      "path": "/"
    },
    {
      "title": "scrapy爬取小红书实战",
      "frontmatter": {
        "title": "scrapy爬取小红书实战",
        "date": "2025-07-02T00:00:00.000Z",
        "categories": [
          "AI程序设计实训"
        ],
        "tags": [
          "AI"
        ]
      },
      "regularPath": "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E7%88%AC%E5%8F%96%E5%B0%8F%E7%BA%A2%E4%B9%A6%E5%AE%9E%E6%88%98.html",
      "relativePath": "blogs/AI程序设计实训/数据爬取/scrapy爬取小红书实战.md",
      "key": "v-4d9f03a0",
      "path": "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/scrapy%E7%88%AC%E5%8F%96%E5%B0%8F%E7%BA%A2%E4%B9%A6%E5%AE%9E%E6%88%98.html"
    },
    {
      "title": "敲代码敲累了的感想",
      "frontmatter": {
        "title": "敲代码敲累了的感想",
        "date": "2025-06-30T00:00:00.000Z",
        "categories": [
          "博客"
        ],
        "tags": [
          "随笔",
          "计算机"
        ],
        "sticky": 2
      },
      "regularPath": "/blogs/%E5%8D%9A%E5%AE%A2/%E6%84%9F%E6%83%B3.html",
      "relativePath": "blogs/博客/感想.md",
      "key": "v-53e1722a",
      "path": "/blogs/%E5%8D%9A%E5%AE%A2/%E6%84%9F%E6%83%B3.html",
      "headers": [
        {
          "level": 2,
          "title": "计算机最需要的能力是快速学习掌握新技术的能力",
          "slug": "计算机最需要的能力是快速学习掌握新技术的能力"
        }
      ]
    },
    {
      "title": "xpath",
      "frontmatter": {
        "title": "xpath",
        "date": "2025-07-02T00:00:00.000Z",
        "categories": [
          "AI程序设计实训"
        ],
        "tags": [
          "AI"
        ]
      },
      "regularPath": "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/xpath.html",
      "relativePath": "blogs/AI程序设计实训/数据爬取/xpath.md",
      "key": "v-10e06d68",
      "path": "/blogs/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/%E6%95%B0%E6%8D%AE%E7%88%AC%E5%8F%96/xpath.html"
    },
    {
      "title": "第一篇博客",
      "frontmatter": {
        "title": "第一篇博客",
        "date": "2025-06-29T00:00:00.000Z",
        "categories": [
          "博客"
        ],
        "tags": [
          "网站建设"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/%E5%8D%9A%E5%AE%A2/1.html",
      "relativePath": "blogs/博客/1.md",
      "key": "v-0ecdade6",
      "path": "/blogs/%E5%8D%9A%E5%AE%A2/1.html",
      "headers": [
        {
          "level": 2,
          "title": "本站建站方式",
          "slug": "本站建站方式"
        }
      ]
    },
    {
      "title": "捞女游戏游玩感想",
      "frontmatter": {
        "title": "捞女游戏游玩感想",
        "date": "2025-06-30T00:00:00.000Z",
        "categories": [
          "游戏测评"
        ],
        "tags": [
          "游戏"
        ]
      },
      "regularPath": "/blogs/%E5%8D%9A%E5%AE%A2/%E6%B8%B8%E6%88%8F%E6%B5%8B%E8%AF%84/%E6%8D%9E%E5%A5%B3%E6%B8%B8%E6%88%8F.html",
      "relativePath": "blogs/博客/游戏测评/捞女游戏.md",
      "key": "v-64ac6d72",
      "path": "/blogs/%E5%8D%9A%E5%AE%A2/%E6%B8%B8%E6%88%8F%E6%B5%8B%E8%AF%84/%E6%8D%9E%E5%A5%B3%E6%B8%B8%E6%88%8F.html"
    },
    {
      "title": "venv配置python虚拟环境",
      "frontmatter": {
        "title": "venv配置python虚拟环境",
        "date": "2025-06-30T00:00:00.000Z",
        "categories": [
          "编程环境配置"
        ],
        "tags": [
          "python",
          "环境配置"
        ]
      },
      "regularPath": "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/venv.html",
      "relativePath": "blogs/编程环境搭建/python环境搭建/venv.md",
      "key": "v-09512f34",
      "path": "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/venv.html"
    },
    {
      "title": "微信小程序自定义tabBar教程",
      "frontmatter": {
        "title": "微信小程序自定义tabBar教程",
        "date": "2025-06-30T00:00:00.000Z",
        "categories": [
          "微信小程序"
        ],
        "tags": null,
        "sticky": 3
      },
      "regularPath": "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89tabBar%E6%95%99%E7%A8%8B.html",
      "relativePath": "blogs/微信小程序开发/微信小程序自定义tabBar教程.md",
      "key": "v-40324584",
      "path": "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89tabBar%E6%95%99%E7%A8%8B.html"
    },
    {
      "title": "VuePress热重载不成功的问题解决",
      "frontmatter": {
        "title": "VuePress热重载不成功的问题解决",
        "date": "2025-06-30T00:00:00.000Z",
        "categories": [
          "网站建设"
        ],
        "tags": [
          "VuePress"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/%E7%BD%91%E7%AB%99%E5%BB%BA%E8%AE%BE/vuepress%E7%83%AD%E9%87%8D%E8%BD%BD%E4%B8%8D%E6%88%90%E5%8A%9F.html",
      "relativePath": "blogs/网站建设/vuepress热重载不成功.md",
      "key": "v-67a046ad",
      "path": "/blogs/%E7%BD%91%E7%AB%99%E5%BB%BA%E8%AE%BE/vuepress%E7%83%AD%E9%87%8D%E8%BD%BD%E4%B8%8D%E6%88%90%E5%8A%9F.html",
      "headers": [
        {
          "level": 2,
          "title": "官网示例代码",
          "slug": "官网示例代码"
        },
        {
          "level": 2,
          "title": "可成功热重载的代码",
          "slug": "可成功热重载的代码"
        }
      ]
    },
    {
      "title": "conda配置python虚拟环境",
      "frontmatter": {
        "title": "conda配置python虚拟环境",
        "date": "2025-06-30T00:00:00.000Z",
        "categories": [
          "编程环境配置"
        ],
        "tags": [
          "python",
          "环境配置"
        ]
      },
      "regularPath": "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/conda.html",
      "relativePath": "blogs/编程环境搭建/python环境搭建/conda.md",
      "key": "v-7562d230",
      "path": "/blogs/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/python%E7%8E%AF%E5%A2%83%E6%90%AD%E5%BB%BA/conda.html",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "conda配置",
          "slug": "conda配置"
        },
        {
          "level": 2,
          "title": "Conda 环境管理",
          "slug": "conda-环境管理"
        },
        {
          "level": 3,
          "title": "创建环境",
          "slug": "创建环境"
        },
        {
          "level": 3,
          "title": "删除环境",
          "slug": "删除环境"
        },
        {
          "level": 3,
          "title": "常用命令",
          "slug": "常用命令"
        },
        {
          "level": 3,
          "title": "包管理",
          "slug": "包管理"
        }
      ]
    },
    {
      "title": "微信小程序开发大经验总结大杂烩",
      "frontmatter": {
        "title": "微信小程序开发大经验总结大杂烩",
        "date": "2025-06-30T00:00:00.000Z",
        "categories": [
          "微信小程序"
        ],
        "tags": null,
        "sticky": 2
      },
      "regularPath": "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E7%BB%8F%E9%AA%8C%E6%80%BB%E7%BB%93.html",
      "relativePath": "blogs/微信小程序开发/微信小程序开发经验总结.md",
      "key": "v-2663ebee",
      "path": "/blogs/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%BC%80%E5%8F%91%E7%BB%8F%E9%AA%8C%E6%80%BB%E7%BB%93.html",
      "headers": [
        {
          "level": 2,
          "title": "1.Skyline渲染引擎问题解决方案（模拟器可以显示图片，真机却不显示）",
          "slug": "_1-skyline渲染引擎问题解决方案-模拟器可以显示图片-真机却不显示"
        },
        {
          "level": 3,
          "title": "问题现象",
          "slug": "问题现象"
        },
        {
          "level": 3,
          "title": "原因分析",
          "slug": "原因分析"
        },
        {
          "level": 3,
          "title": "解决方案",
          "slug": "解决方案"
        },
        {
          "level": 2,
          "title": "2.function（event）",
          "slug": "_2-function-event"
        },
        {
          "level": 2,
          "title": "3.wx.navigateTo() 与 wx.switchTab() 的区别",
          "slug": "_3-wx-navigateto-与-wx-switchtab-的区别"
        },
        {
          "level": 3,
          "title": "wx.navigateTo()",
          "slug": "wx-navigateto"
        },
        {
          "level": 3,
          "title": "wx.switchTab()",
          "slug": "wx-switchtab"
        },
        {
          "level": 3,
          "title": "使用场景",
          "slug": "使用场景"
        },
        {
          "level": 3,
          "title": "注意事项",
          "slug": "注意事项"
        },
        {
          "level": 2,
          "title": "4.自定义tabBar",
          "slug": "_4-自定义tabbar"
        },
        {
          "level": 3,
          "title": "步骤",
          "slug": "步骤"
        },
        {
          "level": 2,
          "title": "5.真机模拟如何本地测试（与后端flask对接）",
          "slug": "_5-真机模拟如何本地测试-与后端flask对接"
        },
        {
          "level": 3,
          "title": "测试步骤：",
          "slug": "测试步骤"
        },
        {
          "level": 2,
          "title": "6.微信code的获取",
          "slug": "_6-微信code的获取"
        },
        {
          "level": 3,
          "title": "步骤：",
          "slug": "步骤-2"
        },
        {
          "level": 2,
          "title": "7.自定义弹窗",
          "slug": "_7-自定义弹窗"
        },
        {
          "level": 3,
          "title": "步骤",
          "slug": "步骤-3"
        },
        {
          "level": 3,
          "title": "使用方法",
          "slug": "使用方法"
        },
        {
          "level": 2,
          "title": "8.json格式的数据获取",
          "slug": "_8-json格式的数据获取"
        },
        {
          "level": 2,
          "title": "9.flask后端路由，要看自定义的prefix",
          "slug": "_9-flask后端路由-要看自定义的prefix"
        },
        {
          "level": 2,
          "title": "10.npm赋能小程序开发",
          "slug": "_10-npm赋能小程序开发"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "AI Tags"
      },
      "regularPath": "/tag/AI/",
      "key": "v-e8d9abc6",
      "path": "/tag/AI/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "随笔 Tags"
      },
      "regularPath": "/tag/%E9%9A%8F%E7%AC%94/",
      "key": "v-1eedfa34",
      "path": "/tag/随笔/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "计算机 Tags"
      },
      "regularPath": "/tag/%E8%AE%A1%E7%AE%97%E6%9C%BA/",
      "key": "v-0cf33b9b",
      "path": "/tag/计算机/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "网站建设 Tags"
      },
      "regularPath": "/tag/%E7%BD%91%E7%AB%99%E5%BB%BA%E8%AE%BE/",
      "key": "v-57230139",
      "path": "/tag/网站建设/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "游戏 Tags"
      },
      "regularPath": "/tag/%E6%B8%B8%E6%88%8F/",
      "key": "v-1571e677",
      "path": "/tag/游戏/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "python Tags"
      },
      "regularPath": "/tag/python/",
      "key": "v-309cc62e",
      "path": "/tag/python/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "环境配置 Tags"
      },
      "regularPath": "/tag/%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/",
      "key": "v-e003d3f8",
      "path": "/tag/环境配置/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "VuePress Tags"
      },
      "regularPath": "/tag/VuePress/",
      "key": "v-5e08fc30",
      "path": "/tag/VuePress/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "AI程序设计实训 Categories"
      },
      "regularPath": "/categories/AI%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E5%AE%9E%E8%AE%AD/",
      "key": "v-bb7c1530",
      "path": "/categories/AI程序设计实训/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "博客 Categories"
      },
      "regularPath": "/categories/%E5%8D%9A%E5%AE%A2/",
      "key": "v-42aee080",
      "path": "/categories/博客/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "游戏测评 Categories"
      },
      "regularPath": "/categories/%E6%B8%B8%E6%88%8F%E6%B5%8B%E8%AF%84/",
      "key": "v-720cd23e",
      "path": "/categories/游戏测评/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "编程环境配置 Categories"
      },
      "regularPath": "/categories/%E7%BC%96%E7%A8%8B%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/",
      "key": "v-997b0f8e",
      "path": "/categories/编程环境配置/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "微信小程序 Categories"
      },
      "regularPath": "/categories/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F/",
      "key": "v-2370bb68",
      "path": "/categories/微信小程序/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "网站建设 Categories"
      },
      "regularPath": "/categories/%E7%BD%91%E7%AB%99%E5%BB%BA%E8%AE%BE/",
      "key": "v-55a3a745",
      "path": "/categories/网站建设/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "友情链接",
        "items": [
          {
            "text": "VuePress教程",
            "link": "https://juejin.cn/post/7189073364365869093"
          }
        ]
      },
      {
        "icon": "reco-github",
        "text": "我的Github",
        "link": "https://github.com/captain798"
      },
      {
        "icon": "reco-email",
        "text": "我的邮箱",
        "link": "mailto:2838651487@qq.com"
      }
    ],
    "subSidebar": "auto",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "博客分类"
      },
      "tag": {
        "location": 3,
        "text": "博客标签"
      }
    },
    "logo": "/captain.jpg"
  }
}