/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "AI": {
      "key": "AI",
      "scope": "tags",
      "path": "/tag/AI/",
      "pageKeys": [
        "v-5bb6f808",
        "v-66154f4d",
        "v-4d9f03a0",
        "v-10e06d68"
      ]
    },
    "随笔": {
      "key": "随笔",
      "scope": "tags",
      "path": "/tag/随笔/",
      "pageKeys": [
        "v-53e1722a"
      ]
    },
    "计算机": {
      "key": "计算机",
      "scope": "tags",
      "path": "/tag/计算机/",
      "pageKeys": [
        "v-53e1722a"
      ]
    },
    "网站建设": {
      "key": "网站建设",
      "scope": "tags",
      "path": "/tag/网站建设/",
      "pageKeys": [
        "v-0ecdade6"
      ]
    },
    "游戏": {
      "key": "游戏",
      "scope": "tags",
      "path": "/tag/游戏/",
      "pageKeys": [
        "v-64ac6d72"
      ]
    },
    "python": {
      "key": "python",
      "scope": "tags",
      "path": "/tag/python/",
      "pageKeys": [
        "v-09512f34",
        "v-7562d230"
      ]
    },
    "环境配置": {
      "key": "环境配置",
      "scope": "tags",
      "path": "/tag/环境配置/",
      "pageKeys": [
        "v-09512f34",
        "v-7562d230"
      ]
    },
    "VuePress": {
      "key": "VuePress",
      "scope": "tags",
      "path": "/tag/VuePress/",
      "pageKeys": [
        "v-67a046ad"
      ]
    }
  },
  "categories": {
    "AI程序设计实训": {
      "key": "AI程序设计实训",
      "scope": "categories",
      "path": "/categories/AI程序设计实训/",
      "pageKeys": [
        "v-5bb6f808",
        "v-66154f4d",
        "v-4d9f03a0",
        "v-10e06d68"
      ]
    },
    "博客": {
      "key": "博客",
      "scope": "categories",
      "path": "/categories/博客/",
      "pageKeys": [
        "v-53e1722a",
        "v-0ecdade6"
      ]
    },
    "游戏测评": {
      "key": "游戏测评",
      "scope": "categories",
      "path": "/categories/游戏测评/",
      "pageKeys": [
        "v-64ac6d72"
      ]
    },
    "编程环境配置": {
      "key": "编程环境配置",
      "scope": "categories",
      "path": "/categories/编程环境配置/",
      "pageKeys": [
        "v-09512f34",
        "v-7562d230"
      ]
    },
    "微信小程序": {
      "key": "微信小程序",
      "scope": "categories",
      "path": "/categories/微信小程序/",
      "pageKeys": [
        "v-40324584",
        "v-2663ebee"
      ]
    },
    "网站建设": {
      "key": "网站建设",
      "scope": "categories",
      "path": "/categories/网站建设/",
      "pageKeys": [
        "v-67a046ad"
      ]
    }
  },
  "timeline": {}
}